name: CI

on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:
    branches: ["*"]

jobs:
  push:
    name: push
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2
        with:
          lfs: true
      - uses: actions/setup-node@v4.1.0
        with:
          node-version: 20
          cache: yarn

      - run: corepack enable
      - run: yarn install --frozen-lockfile
      - run: yarn run build
      - run: yarn run lint:ci
      - run: yarn run test

      - name: Publish to NPM
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
